"""add interpretation and decision timeline tables

Revision ID: 20251215_interpretation_timeline
Revises: 
Create Date: 2025-12-15 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20251215_interpretation_timeline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - manual migration created ###
    op.create_table(
        "interpretation_rules",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True, server_default="0.0"),
        sa.Column("content", postgresql.JSONB(), nullable=True),
        sa.Column("lifecycle", sa.String(length=32), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    op.create_table(
        "decision_timelines",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False, unique=True, index=True),
        sa.Column("timeline_metadata", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    op.create_table(
        "decision_nodes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("timeline_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("decision_timelines.id"), nullable=False, index=True),
        sa.Column("node_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    op.create_table(
        "decision_edges",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("timeline_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("decision_timelines.id"), nullable=False, index=True),
        sa.Column("from_node", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("to_node", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("relation", sa.String(length=64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("decision_edges")
    op.drop_table("decision_nodes")
    op.drop_table("decision_timelines")
    op.drop_table("interpretation_rules")

